import React, { useState } from 'react';
import ImpactCard from '../components/common/ImpactCard';
import ProgressBar from '../components/common/ProgressBar';
import { 
  Leaf, Recycle, Users, Truck, TrendingUp, BarChart2, 
  Droplet, Wind, ShieldCheck, Sparkles, Award, Globe
} from 'lucide-react';
import { GLOBAL_STATS } from '../data/mockData';

export default function ImpactPage() {
  const [activeChartTab, setActiveChartTab] = useState('monthly');

  // Chart dataset
  const monthlyData = [
    { month: 'Apr', donations: 840, wasteKg: 620, kmSaved: 280 },
    { month: 'May', donations: 1120, wasteKg: 890, kmSaved: 390 },
    { month: 'Jun', donations: 1450, wasteKg: 1100, kmSaved: 510 },
    { month: 'Jul', donations: 1980, wasteKg: 1540, kmSaved: 720 },
    { month: 'Aug', donations: 2450, wasteKg: 1890, kmSaved: 880 },
    { month: 'Sep', donations: 3100, wasteKg: 2460, kmSaved: 1140 },
  ];

  const maxVal = 3500;

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-12">
      
      {/* Header */}
      <div className="text-center max-w-3xl mx-auto space-y-3">
        <span className="text-xs font-extrabold uppercase tracking-widest text-emerald-400 bg-emerald-950 px-3.5 py-1.5 rounded-full border border-emerald-800/60">
          Environmental Conservation Analytics
        </span>
        <h1 className="text-3xl sm:text-5xl font-extrabold text-white tracking-tight">
          Sustainability Impact Dashboard
        </h1>
        <p className="text-slate-400 text-xs sm:text-sm">
          Quantifiable ecological savings generated by ReWear Connect smart redistribution network.
        </p>
      </div>

      {/* Large Statistics Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        <ImpactCard
          icon={Leaf}
          title="Textile Waste Prevented"
          value="8.5"
          unit="Tons"
          subtext="Landfill diversion"
          trend="+32% YoY"
          color="emerald"
        />
        <ImpactCard
          icon={Recycle}
          title="Clothes Redistributed"
          value="12,500+"
          unit="items"
          subtext="Garments rehomed"
          trend="96.4% match rate"
          color="cyan"
        />
        <ImpactCard
          icon={Users}
          title="People Supported"
          value="8,200+"
          unit="lives"
          subtext="Shelter beneficiaries"
          trend="150+ partners"
          color="teal"
        />
        <ImpactCard
          icon={Truck}
          title="Transportation Reduced"
          value="3,400"
          unit="km"
          subtext="Route logistics optimized"
          trend="-40% emissions"
          color="amber"
        />
      </div>

      {/* Interactive Charts Section */}
      <div className="glass-panel rounded-3xl p-6 sm:p-10 border border-slate-800 space-y-6">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 border-b border-slate-800 pb-4">
          <div>
            <h3 className="text-lg font-bold text-white flex items-center gap-2">
              <TrendingUp className="w-5 h-5 text-emerald-400" />
              Impact Growth Analytics
            </h3>
            <p className="text-xs text-slate-400">Monthly breakdown of apparel volume and carbon savings</p>
          </div>

          <div className="flex items-center gap-2 bg-slate-950 p-1.5 rounded-2xl border border-slate-800 text-xs font-semibold">
            <button
              onClick={() => setActiveChartTab('monthly')}
              className={`px-3 py-1.5 rounded-xl transition-all ${
                activeChartTab === 'monthly' ? 'bg-emerald-500 text-slate-950 font-bold' : 'text-slate-400 hover:text-white'
              }`}
            >
              Donations Count
            </button>
            <button
              onClick={() => setActiveChartTab('waste')}
              className={`px-3 py-1.5 rounded-xl transition-all ${
                activeChartTab === 'waste' ? 'bg-emerald-500 text-slate-950 font-bold' : 'text-slate-400 hover:text-white'
              }`}
            >
              Waste Diverted (kg)
            </button>
            <button
              onClick={() => setActiveChartTab('travel')}
              className={`px-3 py-1.5 rounded-xl transition-all ${
                activeChartTab === 'travel' ? 'bg-emerald-500 text-slate-950 font-bold' : 'text-slate-400 hover:text-white'
              }`}
            >
              Logistics Saved (km)
            </button>
          </div>
        </div>

        {/* Visual Bar Chart Render */}
        <div className="pt-6 pb-2">
          <div className="h-64 flex items-end justify-between gap-3 sm:gap-6 px-4">
            {monthlyData.map((d) => {
              const val = activeChartTab === 'monthly' ? d.donations : activeChartTab === 'waste' ? d.wasteKg : d.kmSaved;
              const heightPct = Math.min(100, Math.round((val / maxVal) * 100));

              return (
                <div key={d.month} className="flex-1 flex flex-col items-center gap-2 group h-full justify-end">
                  <span className="text-[11px] font-bold text-emerald-400 opacity-0 group-hover:opacity-100 transition-opacity">
                    {val}
                  </span>
                  <div className="w-full bg-slate-800/80 rounded-t-xl overflow-hidden h-full flex items-end p-1 border border-slate-700/50">
                    <div
                      className="w-full rounded-t-lg bg-gradient-to-t from-emerald-600 via-teal-400 to-cyan-300 group-hover:from-emerald-500 group-hover:to-cyan-200 transition-all duration-700 shadow-md shadow-emerald-950/40"
                      style={{ height: `${heightPct}%` }}
                    />
                  </div>
                  <span className="text-xs font-semibold text-slate-400">{d.month}</span>
                </div>
              );
            })}
          </div>
        </div>
      </div>

      {/* Environmental Impact Educational Section */}
      <div className="glass-card rounded-3xl p-8 sm:p-12 border border-slate-800 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-96 h-96 bg-emerald-500/10 blur-[100px] rounded-full pointer-events-none" />

        <div className="max-w-3xl space-y-6">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-950 text-emerald-400 text-xs font-bold border border-emerald-800/60">
            <Globe className="w-4 h-4" />
            <span>Circular Fashion Philosophy</span>
          </div>

          <h2 className="text-2xl sm:text-4xl font-extrabold text-white tracking-tight">
            How Clothing Reuse Saves Planet Resources
          </h2>

          <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
            Producing a single cotton T-shirt consumes approximately 2,700 liters of fresh water and generates 2.6 kg of CO₂ emissions. By extending garment lifecycles through local smart redistribution, ReWear Connect prevents premature textile incineration and reduces raw material demand.
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-4">
            <div className="p-4 rounded-2xl bg-slate-950 border border-slate-800 space-y-2">
              <div className="w-8 h-8 rounded-xl bg-cyan-500/20 text-cyan-400 flex items-center justify-center">
                <Droplet className="w-4 h-4" />
              </div>
              <h4 className="text-sm font-bold text-white">33.7 Million Liters</h4>
              <p className="text-xs text-slate-400">Fresh water saved by redistributing 12,500+ existing garments.</p>
            </div>

            <div className="p-4 rounded-2xl bg-slate-950 border border-slate-800 space-y-2">
              <div className="w-8 h-8 rounded-xl bg-emerald-500/20 text-emerald-400 flex items-center justify-center">
                <Wind className="w-4 h-4" />
              </div>
              <h4 className="text-sm font-bold text-white">32.5 Tons CO₂</h4>
              <p className="text-xs text-slate-400">Carbon offset achieved by eliminating new manufacturing emissions.</p>
            </div>

            <div className="p-4 rounded-2xl bg-slate-950 border border-slate-800 space-y-2">
              <div className="w-8 h-8 rounded-xl bg-teal-500/20 text-teal-300 flex items-center justify-center">
                <Award className="w-4 h-4" />
              </div>
              <h4 className="text-sm font-bold text-white">Zero Landfill Goal</h4>
              <p className="text-xs text-slate-400">100% of usable garments matched to community recipients.</p>
            </div>
          </div>
        </div>
      </div>

    </div>
  );
}
